# Generated by Django 6.0.4 on 2026-04-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='student',
            name='domicile',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
