# Generated by Django 6.0.4 on 2026-04-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_student_qualifications_student_domicile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='domicile',
            new_name='domocile',
        ),
    ]
