# Generated by Django 6.0.4 on 2026-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_domicile_student_domocile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
