# Generated by Django 6.0.4 on 2026-04-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_father_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='district',
        ),
    ]
